
show databases;
create database aug_27;
use aug_27;
create table student(name varchar(25),age int,dob date,address varchar(100));
desc student;
-- insert into tablename values()
insert into student(name,age,dob,address)values("Athul",23,'2001-01-10','Thodupuzha');
insert into student values("Lakshmi",23,'2001-12-24','Thodupuzha');
insert into student(name,age,dob,address)values("Akhila",23,'2001-10-04','Muvattupuzha');
insert into student(name,age,dob,address)values("Basil",23,'2001-10-10','Thodupuzha');
insert into student(name,age,dob,address)values("eldho",23,'2001-04-10','Muvattupuzha');
select * from student;
select name,age from student;
select * from student where name="Athul";
select name,age from student where name="Athul";
create table tbl_student(id int,fristname varchar(20),lastname varchar(20),age int,Grade varchar(10),mark int);
insert into tbl_student values(1,"john","doe",15,"10th",85);
insert into tbl_student values(2,"jane","smith",16,"11th",90);
insert into tbl_student values(3,"alex","brown",14,"9th",75);
insert into tbl_student values(4,"Emily","Davis",15,"10th",88);
insert into tbl_student values(5,"Michael","Johnson",17,"12th",92);
select * from student order by name desc;
update student set address="tvm" where age=23;
delete from student where name="eldho";
create table dept(dept_id int auto_increment primary key,dept_name varchar(25) not null);
insert into dept(dept_name)values("Hr");
insert into dept(dept_name)values("Finance");
insert into dept(dept_name)values("Engineering");
insert into dept(dept_name)values("Markrting");
insert into dept(dept_name)values("Sales");
select * from dept;
desc dept;
create table emp(emp_id int auto_increment primary key,emp_name varchar(25) not null,
emp_age int not null,salary decimal(6,2),dept_id int ,foreign key(dept_id) references dept(dept_id));
desc emp;
insert into emp(emp_name,emp_age,salary,dept_id)values("John Doe",30,6000.00,1);
insert into emp(emp_name,emp_age,salary,dept_id)values("Jane Smith",28,5500.00,2);
insert into emp(emp_name,emp_age,salary,dept_id)values("Mike Brown",35,7500.00,3);
insert into emp(emp_name,emp_age,salary,dept_id)values("Emma Wilson",25,4800.00,4);
insert into emp(emp_name,emp_age,salary,dept_id)values("Liam Johnson",40,8500.00,5);
select * from emp;
insert into dept(dept_name)values("Customer Support");
insert into emp(emp_name,emp_age,salary,dept_id)values("Michael Green",27,6500.00,1);
select * from emp where salary>7000;
select * from emp where dept_id=4;
update emp set salary=9000.00 where emp_name="Liam Johnson";
delete from emp where emp_name="Mike Brown";
delete from dept where dept_id=6;
select * from emp limit 3;
alter table student add phn int;
alter table student drop phn;
alter table student modify column age varchar(25);
desc student;
drop table student;
show tables;
select emp_name,salary from emp where salary>(select avg(salary)from emp);
select dept_name from dept where dept_id in (select dept_id from emp group by dept_id having count(emp_id)>1);
select emp_name from emp where dept_id=(select dept_id from dept where dept_name="Hr");
select dept_name from dept where dept_id>=(select dept_id from emp group by age having max(emp_age)>1);
select * from emp;
